# Generated by Django 5.0.6 on 2024-06-30 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, help_text="Company name", max_length=255, null=True
                    ),
                ),
                (
                    "nip",
                    models.CharField(
                        blank=True, help_text="Nip number", max_length=50, null=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Company name max 255",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "street_address",
                    models.CharField(
                        blank=True,
                        help_text="Street name and building number max 255",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, help_text="Postal code", max_length=20, null=True
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, help_text="City", max_length=100, null=True
                    ),
                ),
                (
                    "voivodeship",
                    models.CharField(
                        blank=True, help_text="Voivodeship", max_length=100, null=True
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, help_text="Country", max_length=100, null=True
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, help_text="Bank name", max_length=255, null=True
                    ),
                ),
                (
                    "bank_address",
                    models.CharField(
                        blank=True, help_text="Bank address", max_length=255, null=True
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        blank=True, help_text="IBAN", max_length=34, null=True
                    ),
                ),
                (
                    "swift",
                    models.CharField(
                        blank=True, help_text="SWIFT", max_length=11, null=True
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
