# Generated by Django 5.0.6 on 2024-06-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company name max 255', max_length=255)),
                ('street', models.CharField(blank=True, help_text='Street name and building number max 255', max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal code', max_length=20, null=True)),
                ('city', models.CharField(blank=True, help_text='City', max_length=100, null=True)),
                ('voivodeship', models.CharField(blank=True, help_text='Voivodeship', max_length=100, null=True)),
                ('country', models.CharField(blank=True, help_text='Country', max_length=100, null=True)),
                ('iban', models.CharField(blank=True, help_text='IBAN', max_length=34, null=True)),
                ('swift', models.CharField(blank=True, help_text='SWIFT', max_length=11, null=True)),
            ],
        ),
    ]
