# Generated by Django 5.0.6 on 2024-06-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('cena', models.CharField(max_length=255)),
                ('nazwa', models.CharField(max_length=255)),
                ('waga', models.IntegerField()),
                ('kodcelny', models.IntegerField()),
            ],
        ),
    ]
