# Generated by Django 5.0.6 on 2024-06-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_invoice', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cena',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='kodcelny',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='nazwa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='waga',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
