# Generated by Django 5.0.6 on 2024-06-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_invoice', '0003_alter_products_cena_alter_products_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('cena', models.CharField(blank=True, max_length=255, null=True)),
                ('nazwa', models.CharField(blank=True, max_length=255, null=True)),
                ('waga', models.IntegerField(blank=True, null=True)),
                ('kodcelny', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
