# Generated by Django 5.0.6 on 2024-06-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_invoice', '0004_product_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('cena', models.CharField(blank=True, max_length=255, null=True)),
                ('nazwa', models.CharField(blank=True, max_length=255, null=True)),
                ('waga', models.IntegerField(blank=True, null=True)),
                ('kodcelny', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
