# Generated by Django 5.0.6 on 2024-06-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_invoice', '0006_alter_products_cena_alter_products_waga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cena',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='waga',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
