# Generated by Django 5.0.6 on 2024-07-02 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generate_invoice", "0008_invoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="date",
        ),
        migrations.AddField(
            model_name="invoice",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invoice",
            name="index",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invoice",
            name="title",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
    ]
